function euler1d_sd2_frames(J,N,P)
%euler1d_frames   Generates snapshots of solution of 1D Euler Eqns 
%   
%   euler1d_frames(N,J,P) where J is the number of grid cells and N the total
%   number of outputs generated by CentPack, loads the output files of 
%   CentPack's  burgers_1d_SD3 example and plots the velocity profile at 
%   dt_out intervals over the length of the simulation
%	
%	CentPack's output is written to the directory 
%
%	CP_root/samples/simulation_MHD1d_SD2/var_files/
%   
%   where var = rho, u1, p, and CP_root stands for your 
%   CentPack installation directory.  The data
%	is loaded into matlab with the built-in load command and ploted over
%	the solution domain, the resulting image is written as a .png file to
%	the directory
% 
%	CP_root/samples/simulation_euler1d_SD2/var_frames/
%	
%	A number of open source tools is available to create an animated sequence
%	of the generated frames, one possiblitiy in UNIX-like systems is to run 
%	the following commands from the command window
%
%	> cd CP_root/samples/simulation_MHD1d_SD2/rho_frames/
%	> convert -adjoin -delay 5 *.png rho_movie.gif
%
%	These will generate the animation rho_movie.gif.
%
%	Remark: convert is a command line application of the open source graphics
%	suite ImageMagick(C), commonly distributed with UNIX-like systems
%	
%	Copyright 2004-2010 Jorge Balbas and Eitan Tadmor 
%   $Revision: 1.0 $  $Date: 2010/04/14
%
caxis(caxis);

x = [];

for p = 0:P-1
    x_file = sprintf('mesh_files/x_p%0.3d', p);
    xp = load(x_file);
    x = [x, xp];
end

for n = 0:N
    rho = [];
    u1 = [];
    press = [];
    
    for p = 0:P-1
        rho_file = sprintf('rho_files/rho_p%0.3d_%0.3d', [p,n]);
        rhop = load(rho_file');
        rho = [rho, rhop];
        
        u1_file = sprintf('u1_files/u1_p%0.3d_%0.3d', [p,n]);
        u1p = load(u1_file');
        u1 = [u1, u1p];
        
        p_file = sprintf('p_files/p_p%0.3d_%0.3d', [p,n]);
        pressp = load(p_file');
        press = [press, pressp];
    end
	
	rho_frame = sprintf('rho_frames/rho_%0.3d', n);
	
	plot(x,rho,'-.', 'LineWidth', 2);
    axis([-1.0 1.0 min(rho)-0.05 max(rho)+0.05]);
	print ('-dpng', '-r0', rho_frame);
    
    u1_frame = sprintf('u1_frames/u1_%0.3d', n);
	
	plot(x,u1,'-.', 'LineWidth', 2);
	axis([-1.0 1.0 min(u1)-0.05 max(u1)+0.05]);
	print ('-dpng', '-r0', u1_frame);
    
    p_frame = sprintf('p_frames/p_%0.3d', n);
	
	plot(x,press,'-.', 'LineWidth', 2);
	axis([-1.0 1.0 min(p)-0.05 max(p)+0.05]);
	print ('-dpng', '-r0', p_frame);
    
    clear rho u1 press;

end;
