function MHD_2d_sd2_frames(J,K,N,P)
%MHD_2d_frames   Generates snapshots of solution of 2D MHD EQNs 
%   
%   MHD_2d_frames(J,K,N,P) where J is the number of grid cells in the 
%   x-direction per processor, K the total number of grid cells in the y- 
%   direction, N the total number of outputs generated by CentPack, and
%   P the number of processors used in the simulation, loads the output 
%   files of CentPack's MHD_2d_SD2 example and plots the density and 
%   pressure countours, and the velocity and magnetic vector fields at 
%   dt_out intervals over the length of the simulation
%	
%	CentPack's output is written to the directory 
%
%	CP_root/samples/MHD_2d_SD2/rho_files/
%   CP_root/samples/MHD_2d_SD2/u1_files/
%   CP_root/samples/MHD_2d_SD2/u2_files/
%   CP_root/samples/MHD_2d_SD2/b1_files/
%   CP_root/samples/MHD_2d_SD2/b2_files/
%   CP_root/samples/MHD_2d_SD2/p_files/
%
%	where CP_root stands for your CentPack installation directory.  The 
%   data is loaded into matlab with the built-in load command and ploted 
%	over the solution domain, the resulting images are written as a .png 
%	files to the directories
% 
%	CP_root/samples/MHD_2d_SD2/rho_frames/
%	CP_root/samples/MHD_2d_SD2/u_frames/
%	CP_root/samples/MHD_2d_SD2/b_frames/
%	CP_root/samples/MHD_2d_SD2/p_frames/
%	
%	A number of open source tools is available to create an animated 
%   sequence of the generated frames, one possiblitiy in UNIX-like systems 
%   is to run the following commands from the command window
%
%	> cd CP_root/samples/euler_2d_FD2/VAR_frames/  (VAR = rho, u, b, p)
%	> convert -adjoin -delay 5 *.png VAR_movie.gif
%
%	These will generate the animation VAR_movie.gif.
%
%	Remark: convert is a command line application of the poen source graphics
%	suite ImageMagick(C), commonly distributed with UNIX-like systems
%	
%	Copyright 2004-2010 Jorge Balbas and Eitan Tadmor 
%   $Revision: 1.0 $  $Date: 2010/04/14
%

caxis(caxis);

x = [];

y = load('mesh_files/y');

for p = 0:P-1
    x_file = sprintf('mesh_files/x_p%0.3d', p);
    xp = load(x_file);
    x = [x, xp];
end

xx = x(1:4:P*J);
yy = y(1:4:K);

for n = 0:N-1

% The following assumes that the numerical results for density, velocity field
% components, etc, that your code generates are in directories called rho_files,
% u1_files, u2_files, etc., with names rho_0, rho_1, rho_23, ..., rho_60 (note
% the single digit in rho_0, rho_1, graphic utilities need that changed to 
% rho_00, ..., rho_09, that's taken care below
    
    rho = [];
	u1 = [];
	u3 = [];
    b1 = [];
	b3 = [];
	press = [];
	
    for p = 0:P-1
	
        rho_file = sprintf('rho_files/rho_p%0.3d_%0.3d', [p,n]);
        rhop = load(rho_file');
        rho = [rho; rhop];
        
        u1_file = sprintf('u1_files/u1_p%0.3d_%0.3d', [p,n]);
        u1p = load(u1_file');
        u1 = [u1; u1p];
        
        u3_file = sprintf('u3_files/u3_p%0.3d_%0.3d', [p,n]);
        u3p = load(u3_file');
        u3 = [u3; u3p];
        
        b1_file = sprintf('b1_files/b1_p%0.3d_%0.3d', [p,n]);
        b1p = load(b1_file');
        b1 = [b1; b1p];
        
        b3_file = sprintf('b3_files/b3_p%0.3d_%0.3d', [p,n]);
        b3p = load(b3_file');
        b3 = [b3; b3p];
        
        p_file = sprintf('p_files/p_p%0.3d_%0.3d', [p,n]);
        pp = load(p_file');
        press = [press; pp];

    end
    
    ux = u1(1:4:P*J,1:4:K);
    uy = u3(1:4:P*J,1:4:K);

    bx = b1(1:4:P*J,1:4:K);
    by = b3(1:4:P*J,1:4:K);

    rho_frame = sprintf('rho_frames/rho_%0.3d', n);
    u_frame = sprintf('u_frames/u_%0.3d', n);
    b_frame = sprintf('b_frames/b_%0.3d', n);
    p_frame = sprintf('p_frames/p_%0.3d', n);

    if n > 0
        contourf(x,y,rho',20);
        axis('square');
        print ('-dpng', '-r0', rho_frame);
    end

    quiver(xx,yy,ux',uy',1.5);
    axis([0 2*pi 0 2*pi]);
    axis('square');
    print ('-dpng', '-r0', u_frame);

    quiver(xx,yy,bx',by',1.5);
    axis([0 2*pi 0 2*pi]);
    axis('square');
    print ('-dpng', '-r0', b_frame);

    contourf(x,y,press',20);
    axis([0 2*pi 0 2*pi]);
    axis('square');
    print ('-dpng', '-r0', p_frame);
    
    clear rho u1 u3 ux uy b1 b3 bx by press;

end;