function euler2d_fd2_frames(J,K,N,P)
%euler2d_frames   Generates snapshots of solution of 2D Euler's EQNs 
%   
%   euler_2d_frames(J,K,N,P) where J is the number of grid cells in the 
%   x-direction per processor, K the total number of grid cells in the y- 
%   direction, N the total number of outputs generated by CentPack, and
%   P the number of processors used in the simulation, loads the output 
%   files of CentPack's euler_2d_FD2 example 
%   and plots the density and pressure countours, and the velocity field 
%   at dt_out intervals over the length of the simulation
%	
%	CentPack's output is written to the directory 
%
%	CP_root/samples/euler_2d_FD2/rho_files/
%   CP_root/samples/euler_2d_FD2/u1_files/
%   CP_root/samples/euler_2d_FD2/u2_files/
%   CP_root/samples/euler_2d_FD2/p_files/
%
%	where CP_root stands for your CentPack installation directory.  The 
%   data is loaded into matlab with the built-in load command and ploted 
%	over the solution domain, the resulting images are written as a .png 
%	files to the directories
% 
%	CP_root/samples/euler_2d_FD2/rho_frames/
%	CP_root/samples/euler_2d_FD2/u_frames/
%	CP_root/samples/euler_2d_FD2/p_frames/
%	
%	A number of open source tools is available to create an animated 
%   sequence of the generated frames, one possiblitiy in UNIX-like systems 
%   is to run the following commands from the command window
%
%	> cd CP_root/samples/euler_2d_FD2/VAR_frames/  (VAR = rho, u, p)
%	> convert -adjoin -delay 5 *.png VAR_movie.gif
%
%	These will generate the animation VAR_movie.gif.
%
%	Remark: convert is a command line application of the poen source graphics
%	suite ImageMagick(C), commonly distributed with UNIX-like systems
%	
%	Copyright 2004-2011 Jorge Balbas and Eitan Tadmor 
%   $Revision: 1.0 $  $Date: 2011/05/14
%

caxis(caxis);

xo = [];
xe = [];

yo = load('mesh_files/yo');
ye = load('mesh_files/ye');

for p = 0:P-1
    xo_file = sprintf('mesh_files/xo_p%0.3d', p);
    xpo = load(xo_file);
    xo = [xo, xpo];
    
    xe_file = sprintf('mesh_files/xe_p%0.3d', p);
    xpe = load(xe_file);
    xe = [xe, xpe];
end

xxe = xe(1:5:P*J);
xxo = xo(1:5:P*J);
yye = ye(1:5:K);
yyo = yo(1:5:K);

for n = 0:N

	rho = [];
	u1 = [];
	u2 = [];
	press = [];
	
    for p = 0:P-1
        rho_file = sprintf('rho_files/rho_p%0.3d_%0.3d', [p,n]);
        rhop = load(rho_file');
        rho = [rho; rhop];
		
		u1_file = sprintf('u1_files/u1_p%0.3d_%0.3d', [p,n]);
        u1p = load(u1_file');
        u1 = [u1; u1p];
		
		u2_file = sprintf('u2_files/u2_p%0.3d_%0.3d', [p,n]);
        u2p = load(u2_file');
        u2 = [u2; u2p];
		
		p_file = sprintf('p_files/p_p%0.3d_%0.3d', [p,n]);
        pp = load(p_file');
        press = [press; pp];
    end
    
    odd_file = sprintf('odd_files/odd_%0.3d', n);
    odd = load(odd_file);
    
	%if odd
        x = xo;
        y = yo;
        xx = xxo;
        yy = yyo;
    %else
    %    x = xe;
    %    y = ye;
    %    xx = xxe;
    %    yy = yye;
    %end
	
	ux = u1(1:5:P*J,1:5:K);
	uy = u2(1:5:P*J,1:5:K);
	
	rho_frame = sprintf('rho_frames/rho_%0.3d', n);
    u_frame = sprintf('u_frames/u_%0.3d', n);
	p_frame = sprintf('p_frames/p_%0.3d', n);
	
	contour(x,y,rho',20);
    axis([0 1 0 1]);
    axis('square')
	print ('-dpng', '-r0', rho_frame);
	
	quiver(xx,yy,ux',uy',1.5);
	axis([0 1 0 1]);
    axis('square')
	print ('-dpng', '-r0', u_frame);
	
	contour(x,y,press',20);
    axis([0 1 0 1]);
    axis('square')
	print ('-dpng', '-r0', p_frame);
	
	clear rho u1 u2 ux uy press;

end;