function scalar2d_sd2_frames(J,K,N,P)
%scalar2d_frames   Generates snapshots of solution of 2D Tadmor-Tao model 
%   
%   scalar2d_frames(N,J,K,P) where J is the number of grid cells in the 
%   x-direction per processor, K the total number of grid cells in the y- 
%   direction, N the total number of outputs generated by CentPack, and
%   P the number of processors used in the simulation, loads the output 
%   files of CentPack's scalar2d_SD2 example and plots contours of the 
%   solution at dt_out intervals over the length of the simulation
%	
%	CentPack's output is written to the directory 
%
%	CP_root/samples/scalar2d_SD2/u_files/
%   
%	where CP_root stands for your CentPack installation directory.  The data
%	is loaded into matlab with the built-in load command and ploted over
%	the solution domain, the resulting image is written as a .png file to
%	the directory
% 
%	CP_root/samples/scalar2d_SD2/u_frames/
%	
%	A number of open source tools is available to create an animated sequence
%	of the generated frames, one possiblitiy in UNIX-like systems is to run 
%	the following commands from the command window
%
%	> cd CP_root/samples/scalar2d_SD2/u_frames/
%	> convert -adjoin -delay 5 *.png u_movie.gif
%
%	These will generate the animation u_movie.gif.
%
%	Remark: convert is a command line application of the open source graphics
%	suite ImageMagick(C), commonly distributed with UNIX-like systems
%	
%	Copyright 2004-2010 Jorge Balbas and Eitan Tadmor 
%   $Revision: 1.0 $  $Date: 2010/04/14
%
caxis(caxis);

x = [];

y = load('mesh_files/y');

for p = 0:P-1
    x_file = sprintf('mesh_files/x_p%0.3d', p);
    xp = load(x_file);
    x = [x, xp];
end

for n = 0:N
    u = [];
    for p = 0:P-1
        u_file = sprintf('u_files/u_p%0.3d_%0.3d', [p,n]);
        up = load(u_file');
        u = [u; up];
    end
	
	u_frame = sprintf('u_frames/u_%0.3d', n);
	
	contour(x,y,u',20);
	axis([0.0 2.0*pi 0.0 2.0*pi]);
	print ('-dpng', '-r0', u_frame);
    clear u;

end;
